definitions:
  database.Event:
    properties:
      date:
        type: string
      description:
        maxLength: 200
        minLength: 10
        type: string
      id:
        type: integer
      location:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      ownerId:
        type: integer
    required:
    - date
    - description
    - location
    - name
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
  description: API para la gestión de eventos y usuarios en English Corner Academy
  title: English Corner Academy API
  version: "1.0"
paths:
  /api/v1/events:
    get:
      consumes:
      - Application/json
      description: Obtiene una lista de todos los eventos de la database
      produces:
      - Application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Event'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Retorna todos los eventos
      tags:
      - Events
securityDefinitions:
  BearerAuth:
    description: Token de acceso para las operaciones protegidas **Bearer &lt;token&gt;**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
